### ISSUE TITLE
Gon doesn't work in <= Rails 3.1

### ISSUE THREAD

**Issue by yujingz** [gazay/gon#151] opened 2014-07-30 16:12 UTC
Gon uses `request.udid` as a unique id to distinguish requests, but this method was first introduced in Rails 3.2. This makes gon incompatible with any Rails <= 3.1

```
NoMethodError - undefined method `uuid' for #<ActionDispatch::Request:0x007fd4de951518>:
  gon (5.1.2) lib/gon/helpers.rb:49:in `gon_request_uuid'
  gon (5.1.2) lib/gon/helpers.rb:32:in `gon'
```

**Comment by takiy33** [comment] 2015-07-21 15:37
Hello, thank you for issue. I can reproduce the error.

Have you tried the patch?

**Comment by takiy33** [comment] 2015-09-25 12:50
I close this issue because Rails 3.1 is unmaintained by Rails team.

**Closed by takiy33** 2015-09-25 12:50 UTC
